'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),http=require('node:http'),{spawn}=require('node:child_process');
const {createDashboardServer}=require('../src/dashboard');
const CHROME=[process.env.CHROME_PATH,'C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'].filter(Boolean).find(fs.existsSync);
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,ms=8000){const end=Date.now()+ms;while(Date.now()<end){try{const value=await fn();if(value)return value}catch{}await wait(50)}throw new Error('browser fixture timeout')}
async function cdp(port){const page=await until(async()=>{const r=await fetch(`http://127.0.0.1:${port}/json`);return (await r.json()).find(p=>p.type==='page')});const ws=new WebSocket(page.webSocketDebuggerUrl);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});let id=0;const pending=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){const [r,j]=pending.get(m.id);pending.delete(m.id);m.error?j(new Error(m.error.message)):r(m.result)}};return {call(method,params={}){return new Promise((r,j)=>{const n=++id;pending.set(n,[r,j]);ws.send(JSON.stringify({id:n,method,params}))})},close(){ws.close()}}}

test('Chrome pointer wizard: pending guards, retry, steps, callback, uninstall, mobile and focus',{skip:CHROME?false:'Chrome not installed',timeout:240000},async()=>{
 const home=fs.mkdtempSync(path.join(process.env.TMPDIR||os.tmpdir(),'santri-browser-'));let chrome,server,remote,mcp,client;
 try{
  remote=http.createServer((req,res)=>{res.setHeader('content-type','application/json');res.end(JSON.stringify(req.url.endsWith('catalog')?{success:true,sources:[],mcpServers:[]}:{success:true,token:'fixture',user:{name:'Browser Fixture',is_premium:true}}))});await new Promise(r=>remote.listen(0,'127.0.0.1',r));
  const githubFetch=async url=>{await wait(250);if(String(url).includes('/repos/fixture/oversized/'))return new Response(JSON.stringify({truncated:true,tree:[]}),{headers:{'content-type':'application/json'}});if(String(url).includes('/repos/fixture/empty/'))return new Response(JSON.stringify({tree:[]}),{headers:{'content-type':'application/json'}});if(String(url).includes('api.github.com/repos/')&&!String(url).includes('/git/trees/'))return new Response(JSON.stringify({default_branch:'main'}),{headers:{'content-type':'application/json'}});return String(url).includes('/git/trees/')?new Response(JSON.stringify({tree:[{path:'demo/SKILL.md',type:'blob'}]}),{headers:{'content-type':'application/json'}}):new Response('---\nname: Demo\ndescription: Browser fixture\n---\nSafe',{headers:{'content-type':'text/plain'}})};
  const bridgeFile=path.join(home,'bridge.json'),controls=[];server=createDashboardServer({cwd:home,home,env:{},bridgeFile,githubFetch,controlRunner:async(action,options)=>{controls.push({action,options});return {ok:true,action,running:false}},apiUrl:`http://127.0.0.1:${remote.address().port}/api`});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`,post=(url,body={})=>fetch(base+url,{method:'POST',headers:{origin:base,'content-type':'application/json'},body:JSON.stringify(body)});
  const login=await(await post('/api/auth/login')).json(),state=new URL(login.url).searchParams.get('state');await post('/api/auth/callback',{state,ticket:'fixture_ticket'});
  const config=path.join(home,'.gemini','config','mcp_config.json');fs.mkdirSync(path.dirname(config),{recursive:true});fs.writeFileSync(config,JSON.stringify({mcpServers:{'santri-skills':{command:process.execPath,args:[path.resolve(__dirname,'../bin/cli.js'),'mcp-serve']}}}));
  const debug=29000+Math.floor(Math.random()*1000),profile=path.join(home,'chrome');chrome=spawn(CHROME,['--headless=new','--disable-gpu','--no-sandbox',`--remote-debugging-port=${debug}`,`--user-data-dir=${profile}`,base],{stdio:'ignore'});client=await cdp(debug);
  const run=async expression=>{const result=await client.call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.exception?.description||result.exceptionDetails.text);return result.result.value};
  const pointer=async selector=>{await until(()=>run("!document.querySelector('.wizard-enter')&&!document.querySelector('dialog.dialog-closing')&&[...document.querySelectorAll('dialog[open]')].every(d=>!d.getAnimations().some(a=>a.playState==='running'))"));const point=await run(`(()=>{const b=document.querySelector(${JSON.stringify(selector)});b.scrollIntoView({block:'center',behavior:'instant'});const r=b.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`);await client.call('Input.dispatchMouseEvent',{type:'mouseMoved',...point});await client.call('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...point});await client.call('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...point})};
  const key=async(key,code=key)=>{const codes={Enter:13,Escape:27,Tab:9,' ':32},text=key==='Enter'?'\r':key===' '?' ':undefined;for(const type of ['keyDown','keyUp'])await client.call('Input.dispatchKeyEvent',{type,key,code,text:type==='keyDown'?text:undefined,windowsVirtualKeyCode:codes[key]||0})};
  const setUrl=async value=>run(`(()=>{const el=document.querySelector('#wizard-url');el.value=${JSON.stringify(value)};el.dispatchEvent(new Event('input',{bubbles:true}));el.focus()})()`);
  const stage=async name=>until(()=>run(`document.querySelector('#wizard-stage').textContent===${JSON.stringify(name)}`));
  const snapshot=async name=>{const dir=process.env.WIZARD_SCREENSHOT_DIR||path.join(process.env.TMPDIR||os.tmpdir(),'santrihub-wizard-evidence');fs.mkdirSync(dir,{recursive:true});const file=path.join(dir,name+'.png');const shot=await client.call('Page.captureScreenshot',{format:'png'});fs.writeFileSync(file,Buffer.from(shot.data,'base64'));console.log('Screenshot: '+file)};
  const noOverflow=async id=>assert.equal(await run(`(()=>{const d=document.querySelector(${JSON.stringify(id)}),r=d.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight&&d.scrollWidth<=d.clientWidth+1&&d.querySelector('.wizard-body').scrollWidth<=d.querySelector('.wizard-body').clientWidth+1})()`),true);
  await until(()=>run("document.querySelector('#add-item')&&!document.querySelector('#content').hidden"));
  await client.call('Emulation.setDeviceMetricsOverride',{width:1280,height:900,deviceScaleFactor:1,mobile:false});
  // Repository bookmarks read preview only, never install.
  await pointer('[data-page=repos]');await until(()=>run("document.querySelectorAll('#repo-sources .catalog-card').length===3"));assert.match(await run("document.querySelector('#repo-sources').textContent"),/MONOREPO-SKILLS.*GOOGLE-APPSCRIPT-SKILLS.*SANTRI-SKILLS/s);assert.notEqual(await run("getComputedStyle(document.querySelector('#add-repo')).backgroundColor"),'rgba(0, 0, 0, 0)');await pointer('#add-repo');await until(()=>run("document.querySelector('#repo-modal').open"));
  assert.equal(await run("getComputedStyle(document.querySelector('#repo-modal')).animationName"),'dialog-bubble-in');assert.equal(await run('document.activeElement.id'),'repo-modal-url');
  await run("document.querySelector('#repo-modal-url').value='https://github.com/Fixture/Repo';document.querySelector('#repo-modal-url').dispatchEvent(new Event('input'))");assert.equal(await run("document.querySelector('#repo-modal-save').disabled"),false);await pointer('#repo-modal-save');await until(()=>run("!document.querySelector('#repo-modal').open&&document.querySelector('#saved-repos .catalog-card')"));
  assert.equal(await run("getComputedStyle(document.querySelector('#saved-repos')).display"),'grid');assert.match(await run("document.querySelector('#saved-repos').textContent"),/Skills 1 · MCP 0/);
  await pointer('#add-repo');for(const width of [320,390,1024,1440]){await client.call('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:width<600});await wait(450);await noOverflow('#repo-modal')}await key('Escape');await until(()=>run("!document.querySelector('#repo-modal').open"));
  await run("window.copiedRepo=null;Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.copiedRepo=text}}})");await pointer('#saved-repos .copy-btn');assert.equal(await run('copiedRepo'),'https://github.com/fixture/repo');assert.equal(await run("document.querySelector('#saved-repos .copy-btn').textContent"),'Tersalin');
  await client.call('Emulation.setDeviceMetricsOverride',{width:320,height:900,deviceScaleFactor:1,mobile:true});await wait(450);assert.equal(await run("document.documentElement.scrollWidth<=innerWidth"),true);
  await pointer('#saved-repos .repo-delete');await until(()=>run("!document.querySelector('#saved-repos .catalog-card')"));await pointer('#add-repo');await key('Tab');assert.equal(await run("document.activeElement.closest('#repo-modal')!==null"),true);await key('Escape');await until(()=>run("!document.querySelector('#repo-modal').open"));assert.equal(await run('document.activeElement.id'),'add-repo');
  await client.call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await pointer('#add-repo');assert.equal(await run("getComputedStyle(document.querySelector('#repo-modal')).animationName"),'none');await key('Escape');await until(()=>run("!document.querySelector('#repo-modal').open"));await client.call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'no-preference'}]});await client.call('Emulation.setDeviceMetricsOverride',{width:1280,height:900,deviceScaleFactor:1,mobile:false});
  // Status Config follows external disk changes; no install route used here.
  await run("catalog.skills=[{id:'external-live'},{id:'missing-live'}];catalog.mcpServers.push({id:'missing-live-mcp'});go('status')");
  await until(()=>run("document.querySelector('#status-view').textContent.includes('missing-live')"));
  assert.equal(await run("document.querySelectorAll('#status-view > article').length===2&&document.querySelectorAll('#page-status .status-guide').length===1&&document.querySelectorAll('#page-status .status-guide details').length===3"),true);
  const liveDir=path.join(home,'.gemini','config','skills','external-live');fs.mkdirSync(liveDir,{recursive:true});fs.writeFileSync(path.join(liveDir,'SKILL.md'),'External live fixture');
  await until(()=>run("[...document.querySelectorAll('#status-view .disk-row')].some(r=>r.textContent.includes('external-live')&&r.textContent.includes('FILE ADA'))"));
  assert.equal(await run("[...document.querySelectorAll('#status-view .disk-row')].some(r=>r.textContent.includes('missing-live')&&r.querySelector('.pill.bad')?.textContent==='BELUM ADA')"),true);
  fs.rmSync(liveDir,{recursive:true});await until(()=>run("[...document.querySelectorAll('#status-view .disk-row')].some(r=>r.textContent.includes('external-live')&&r.querySelector('.pill.bad')?.textContent==='BELUM ADA')"));
  await run("window.statusReads=0;window.statusFetch=fetch;window.fetch=function(url,options){if(String(url).startsWith('/api/status?'))statusReads++;return statusFetch.call(this,url,options)}");
  await pointer('#open-advanced');assert.equal(await run('document.activeElement.id'),'close-advanced');assert.equal(await run("getComputedStyle(document.querySelector('#advanced-status')).animationName"),'dialog-bubble-in');
  for(const width of [320,390,1280]){await client.call('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:width<600});await wait(450);await noOverflow('#advanced-status');assert.equal(await run("document.documentElement.scrollWidth<=innerWidth"),true)}
  await key('Tab');assert.equal(await run("document.activeElement.closest('#advanced-status')!==null"),true);await key('Escape');await until(()=>run("!document.querySelector('#advanced-status').open"));assert.equal(await run('document.activeElement.id'),'open-advanced');
  await client.call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await pointer('#open-advanced');assert.equal(await run("getComputedStyle(document.querySelector('#advanced-status')).animationName"),'none');await key('Escape');await until(()=>run("!document.querySelector('#advanced-status').open"));
  await client.call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'no-preference'}]});await run("catalog.mcpServers=catalog.mcpServers.filter(x=>x.id!=='missing-live-mcp');go('home')");const stoppedReads=await run('statusReads');await wait(2200);assert.equal(await run('statusReads'),stoppedReads);
  await client.call('Emulation.setDeviceMetricsOverride',{width:1280,height:900,deviceScaleFactor:1,mobile:false});
  // Delay real requests, never synthesize success. Count writes to prove no duplicate submission.
  await run("window.writes={install:0,uninstall:0};window.originalFetch=window.fetch;window.fetch=async function(url,options){if(String(url).includes('/api/github/install')){writes.install++;await new Promise(r=>setTimeout(r,350))}if(String(url).includes('/api/uninstall')){writes.uninstall++;await new Promise(r=>setTimeout(r,350))}return originalFetch.call(this,url,options)}");
  assert.equal(await run("document.querySelector('#add-item').closest('#page-home')!==null && document.querySelector('main > header #add-item')===null && document.querySelector('#add-item').compareDocumentPosition(document.querySelector('.home-section'))===4"),true);
  // Cek & Tes: inventory only on open; explicit callback, server expiry, real fixture evidence.
  await run("window.checkRequests={verify:0,start:0,status:0};window.checkFetch=fetch;window.fetch=async function(url,options){for(const [key,path] of Object.entries({verify:'/api/verify',start:'/api/verification/start',status:'/api/verification/status'}))if(String(url)===path)checkRequests[key]++;return checkFetch.call(this,url,options)}");
  const checkStage=async name=>until(()=>run(`document.querySelector('#check-stage').textContent===${JSON.stringify(name)}&&!document.querySelector('#check-panel').getAttribute('aria-busy').includes('true')`));
  const beforeCheck=fs.readFileSync(config,'utf8');
  await pointer('#check-test');await checkStage('Inventaris');assert.equal(await run('checkRequests.start'),0);assert.equal(fs.existsSync(bridgeFile),false);assert.equal(fs.readFileSync(config,'utf8'),beforeCheck);
  assert.equal(await run("[...document.querySelectorAll('#check-panel details')].every(d=>!d.open)&&document.querySelectorAll('#check-results details').length===2"),true);
  assert.equal(await run("getComputedStyle(document.querySelector('#check-panel')).animationName"),'dialog-bubble-in');
  for(const width of [320,390,1024,1280,1440]){await client.call('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:width<600});await wait(450);await noOverflow('#check-panel');await snapshot('check-inventory-'+width)}
  await pointer('#check-results details:first-child summary');assert.equal(await run("document.querySelector('#check-results details').open"),true);await noOverflow('#check-panel');
  await pointer('#check-finish');await checkStage('Callback');assert.equal(await run('checkRequests.start'),0);assert.equal(await run("document.querySelector('#check-result').hidden"),true);
  await pointer('#check-start');await until(()=>run("document.querySelector('#check-proof').textContent.includes('Menunggu callback asli')&&!document.querySelector('#check-start').disabled"));assert.equal(await run('checkRequests.start'),1);assert.equal(fs.existsSync(bridgeFile),true);await snapshot('check-pending');
  // Disk binding changes expire actual server challenge, never fabricated status.
  fs.writeFileSync(config,beforeCheck+'\n');await until(()=>run("!document.querySelector('#check-retry').hidden"));assert.match(await run("document.querySelector('#check-proof').textContent"),/kedaluwarsa|berubah/);assert.equal(await run("document.querySelector('#check-stage').textContent"),'Callback');
  fs.writeFileSync(config,beforeCheck);await pointer('#check-retry');await until(()=>run("document.querySelector('#check-proof').textContent.includes('Menunggu callback asli')&&!document.querySelector('#check-start').disabled"));assert.equal(await run('checkRequests.start'),2);
  const capability=JSON.parse(fs.readFileSync(bridgeFile,'utf8'));const accepted=await fetch(base+'/api/verification/bridge',{method:'POST',headers:{'content-type':'application/json','x-santrihub-bridge':capability.token},body:JSON.stringify({challenge:capability.challenge,event:'tool'})});assert.equal(accepted.status,200);
  await checkStage('Hasil');assert.match(await run("document.querySelector('#check-outcome').textContent"),/santri-skills saja.*tidak diautentikasi.*MCP lain dan Skills belum terbukti/s);await snapshot('check-result');await pointer('#check-finish');await until(()=>run("!document.querySelector('#check-panel').open"));assert.equal(await run('document.activeElement.id'),'check-test');
  // Missing prerequisite cannot launch a callback; explicit finish stays unverified.
  fs.rmSync(config);await pointer('#check-test');await checkStage('Inventaris');assert.match(await run("document.querySelector('#check-bridge').textContent"),/belum terkonfigurasi/);await pointer('#check-finish');await checkStage('Callback');assert.equal(await run("document.querySelector('#check-start').disabled"),true);await pointer('#check-finish');await until(()=>run("!document.querySelector('#check-panel').open"));assert.match(await run("document.querySelector('#status').textContent"),/tanpa verifikasi/);assert.equal(await run("document.querySelector('#check-stage').textContent"),'Callback');fs.writeFileSync(config,beforeCheck);
  // ESC cancels pending polling immediately; no request after closing bubble.
  await pointer('#check-test');await checkStage('Inventaris');await pointer('#check-finish');await checkStage('Callback');await pointer('#check-start');await until(()=>run("document.querySelector('#check-proof').textContent.includes('Menunggu callback asli')&&!document.querySelector('#check-start').disabled"));await key('Escape');const polls=await run('checkRequests.status');await until(()=>run("!document.querySelector('#check-panel').open"));await wait(1800);assert.equal(await run('checkRequests.status'),polls);assert.equal(await run('document.activeElement.id'),'check-test');
  // Restart requires user confirmation; cancel never controls real or fixture IDE.
  await pointer('#check-test');await checkStage('Inventaris');await pointer('#check-finish');await checkStage('Callback');await pointer('#restart-antigravity');await until(()=>run("document.querySelector('#restart-confirm').open"));assert.deepEqual(controls,[]);await key('Escape');await until(()=>run("!document.querySelector('#restart-confirm').open"));assert.deepEqual(controls,[]);
  await client.call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});assert.equal(await run("getComputedStyle(document.querySelector('#check-panel')).animationName"),'none');await pointer('#close-check');await until(()=>run("!document.querySelector('#check-panel').open"));assert.equal(await run('document.activeElement.id'),'check-test');await client.call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'no-preference'}]});
  for(const width of [320,390,1024,1280,1440]){await client.call('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:width<600});await wait(450);assert.equal(await run("(()=>{const h=document.querySelector('main > header'),b=document.querySelector('#check-test').getBoundingClientRect();return h.contains(document.querySelector('.scope-bar'))&&h.scrollWidth<=h.clientWidth+1&&b.left>=0&&b.right<=innerWidth&&document.documentElement.scrollWidth<=innerWidth})()"),true,`topbar at ${width}`);await snapshot('topbar-'+width)}
  await client.call('Emulation.setDeviceMetricsOverride',{width:1280,height:900,deviceScaleFactor:1,mobile:false});
  await pointer('[data-page=skills]');await until(()=>run("!document.querySelector('#page-skills').hidden&&!document.querySelector('#page-skills').inert"));
  assert.equal(await run("!document.querySelector('#page-skills .local-import')&&!document.querySelector('#page-skills .catalog-grid')"),true);
  await pointer('#open-skills-catalog');await until(()=>run("document.querySelector('#catalog-modal').open"));
  // Catalog confirmation must intercept pointer install before any network write.
  await run("window.catalogWrites={skills:0,mcp:0};window.catalogFetch=fetch;window.fetch=function(url,options){if(options?.method==='POST'&&String(url)==='/api/install')catalogWrites.skills++;if(options?.method==='POST'&&String(url)==='/api/mcp')catalogWrites.mcp++;return catalogFetch.call(this,url,options)};catalog.skills=[{id:'fixture-skill',label:'Fixture Skill',source:'Fixture'}];renderCatalog()");
  await pointer('#catalog-items input');await pointer('#catalog-install');
  assert.equal(await run("!document.querySelector('#catalog-confirm').hidden"),true);
  assert.equal(await run('catalogWrites.skills'),0);
  assert.equal(await run("document.activeElement.id"),'catalog-confirm-cancel');
  await key('Tab');assert.equal(await run('document.activeElement.id'),'catalog-confirm-submit');await key('Tab');assert.equal(await run('document.activeElement.id'),'catalog-confirm-cancel');
  assert.equal(await run("[...document.querySelector('#catalog-modal').children].filter(el=>el.id!=='catalog-confirm').every(el=>el.inert)"),true);
  assert.equal(await run("getComputedStyle(document.querySelector('#catalog-confirm-panel')).animationName"),'dialog-bubble-in');
  assert.match(await run("document.querySelector('#catalog-confirm').textContent"),/Skills.*1.*Fixture Skill.*GLOBAL/s);
  await key('Escape');await until(()=>run("document.querySelector('#catalog-confirm').hidden"));
  assert.equal(await run('catalogWrites.skills'),0);assert.equal(await run('document.activeElement.id'),'catalog-install');
  await pointer('#catalog-install');await until(()=>run("!document.querySelector('#catalog-confirm').hidden"));
  await client.call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});assert.equal(await run("getComputedStyle(document.querySelector('#catalog-confirm-panel')).animationName"),'none');
  await client.call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'no-preference'}]});
  await pointer('#catalog-confirm-submit');await until(()=>run('catalogWrites.skills>0'));
  assert.equal(await run('catalogWrites.skills'),1);
  await until(()=>run("document.querySelector('#catalog-confirm').hidden&&document.querySelector('#catalog-modal').getAttribute('aria-busy')!=='true'"));
  await run("selectedSkills.clear();loadStatus()");
  if(!await run("document.querySelector('#catalog-modal').open"))await pointer('#open-skills-catalog');
  await until(()=>run("document.querySelector('#catalog-modal').open"));
  assert.equal(await run("getComputedStyle(document.querySelector('#catalog-modal')).animationName"),'dialog-bubble-in');
  assert.equal(await run("document.querySelector('#catalog-title').textContent"),'Katalog Skills');
  await pointer('#catalog-close');await until(()=>run("!document.querySelector('#catalog-modal').open"));
  await pointer('[data-page=mcp]');await until(()=>run("!document.querySelector('#page-mcp').hidden&&!document.querySelector('#page-mcp').inert"));
  await pointer('#open-mcp-catalog');await until(()=>run("document.querySelector('#catalog-modal').open"));
  assert.equal(await run("document.querySelector('#catalog-title').textContent"),'Katalog MCP Servers');
  assert.equal(await run("document.querySelector('#catalog-items input')===null"),true);assert.equal(await run("document.querySelector('#catalog-install').disabled"),true);
  await run("lastStatus.mcp.servers=[];renderCatalog()");await pointer('#catalog-items input');assert.equal(await run("document.querySelector('#catalog-count').textContent"),'1 dipilih');assert.equal(await run("document.querySelector('#catalog-install').disabled"),false);
  await pointer('#catalog-install');assert.equal(await run("document.querySelector('#catalog-confirm-submit').textContent"),'Konfirmasi Daftarkan');assert.match(await run("document.querySelector('#catalog-confirm').textContent"),/MCP Servers.*1.*GLOBAL.*sumber tepercaya/s);assert.equal(await run('catalogWrites.mcp'),0);
  await client.call('Emulation.setDeviceMetricsOverride',{width:320,height:740,deviceScaleFactor:1,mobile:true});await wait(50);assert.equal(await run("(()=>{const p=document.querySelector('#catalog-confirm-panel').getBoundingClientRect();return p.left>=0&&p.right<=innerWidth&&p.top>=0&&p.bottom<=innerHeight&&document.querySelector('#catalog-confirm-panel').scrollWidth<=document.querySelector('#catalog-confirm-panel').clientWidth+1})()"),true);
  await key('Escape');assert.equal(await run('catalogWrites.mcp'),0);await until(()=>run("document.querySelector('#catalog-confirm').hidden"));await client.call('Emulation.setDeviceMetricsOverride',{width:1280,height:900,deviceScaleFactor:1,mobile:false});
  await pointer('#catalog-install');await pointer('#catalog-confirm-cancel');await until(()=>run("document.querySelector('#catalog-confirm').hidden"));assert.equal(await run('catalogWrites.mcp'),0);
  await pointer('#catalog-install');await pointer('#catalog-confirm-submit');await until(()=>run('catalogWrites.mcp===1'));await until(()=>run("!document.querySelector('#catalog-modal').open"));assert.equal(await run('catalogWrites.mcp'),1);
  await run('selectedSkills.clear();loadStatus()');
  await pointer('[data-page=home]');await until(()=>run("!document.querySelector('#page-home').hidden&&!document.querySelector('#page-home').inert"));
  await pointer('#add-item');await until(()=>run("document.querySelector('#add-chooser').open"));await snapshot('choice-desktop');
  await pointer('[data-add-kind=skills]');assert.equal(await run("document.activeElement.id"),'wizard-url');assert.equal(await run("document.querySelector('#wizard-next').disabled"),true);
  await run('window.fixtureFetch=window.fetch');
  for(const [message,expected] of [['Fallback arsip gagal: Symlink/hardlink/tipe arsip ditolak.','Fallback arsip gagal: Symlink/hardlink/tipe arsip ditolak.'],['Artefak arsip terlalu besar.','Artefak arsip terlalu besar.'],['fetch failed','Repository belum dapat diakses dengan aman. Periksa URL dan koneksi, lalu coba Preview lagi.']]){
   await run(`window.fetch=async function(url,options){if(String(url).includes('/api/github/preview'))return new Response(JSON.stringify({error:${JSON.stringify(message)}}),{status:400});return originalFetch.call(this,url,options)}`);await setUrl('https://github.com/fixture/error/tree/main');await key('Enter');await until(()=>run("document.querySelector('#wizard-feedback').dataset.error==='true'&&!document.querySelector('#wizard-scan').disabled"));assert.equal(await run("document.querySelector('#wizard-feedback').textContent"),expected);
  }
  await run('window.fetch=async function(url,options){if(String(url).includes("/api/github/preview"))return new Response(JSON.stringify({classification:"unscannable",skills:[],mcp:[],note:"Repository valid, tetapi struktur arsip tidak dapat dipindai aman. Tidak ada item yang dipasang."}),{status:200,headers:{"content-type":"application/json"}});return fixtureFetch.call(this,url,options)}');await setUrl('https://github.com/fixture/unscannable/tree/main');await key('Enter');await until(()=>run("document.querySelector('#wizard-feedback').textContent.includes('struktur arsip')&&!document.querySelector('#wizard-scan').disabled"));assert.equal(await run("document.querySelector('#wizard-feedback').textContent==='Repository valid, tetapi struktur arsip tidak dapat dipindai aman. Tidak ada item yang dipasang.'&&document.querySelector('#wizard-next').disabled&&!document.querySelector('#wizard-results input')"),true);
  await run('window.fetch=fixtureFetch');
  assert.equal(await run("(()=>{const d=document.querySelector('#install-wizard'),rail=d.querySelector('.wizard-rail').getBoundingClientRect(),main=d.querySelector('.wizard-main').getBoundingClientRect(),stepper=d.querySelector('.wizard-stepper').getBoundingClientRect();return getComputedStyle(d).width!=='auto'&&rail.top<main.top&&Math.abs(rail.left-main.left)<2&&Math.abs(rail.width-main.width)<2&&stepper.bottom<=main.top})()"),true);
  assert.equal(await run("document.querySelector('#install-wizard .wizard-stepper li').classList.contains('active')&&document.querySelector('#install-wizard .wizard-stepper li').classList.contains('inactive')===false"),true);
  for(const [repo,note] of [['oversized','terlalu besar untuk dipindai dengan aman'],['empty','tidak menyediakan SKILL.md']]){
   const before=fs.readFileSync(config,'utf8');await setUrl('https://github.com/fixture/'+repo+'/tree/main');await key('Enter');await until(()=>run(`document.querySelector('#wizard-feedback').textContent.includes(${JSON.stringify(note)})&&!document.querySelector('#wizard-scan').disabled`));
   assert.equal(await run("document.querySelector('#wizard-next').disabled&&document.querySelector('#wizard-selection').hidden&&!document.querySelector('#wizard-results input')&&document.querySelector('#wizard-feedback').dataset.error==='false'"),true);assert.equal(await run('writes.install'),0);assert.equal(fs.readFileSync(config,'utf8'),before);
  }
  await setUrl('https://github.com/fixture/repo/tree/main');await key('Enter');
  await until(()=>run("!document.querySelector('#wizard-loading').hidden"));
  assert.equal(await run("['wizard-next','wizard-close','wizard-cancel','wizard-url','wizard-scan'].every(id=>document.getElementById(id).disabled)&&!document.querySelector('#wizard-loading progress').hasAttribute('value')"),true);
  await key('Escape');assert.equal(await run("document.querySelector('#install-wizard').open"),true);await snapshot('scan-pending');
  await until(()=>run("document.querySelector('#wizard-results input')&&!document.querySelector('#wizard-scan').disabled"));
  // Native checkbox remains keyboard-operable despite custom visual.
  await run("document.querySelector('#wizard-results input').focus()");await key(' ','Space');assert.equal(await run("document.querySelector('#wizard-count').textContent"),'1 dari 1 dipilih');
  await pointer('#wizard-next');await stage('Activation');assert.equal(await run("document.activeElement.id"),'wizard-stage');assert.equal(await run("document.querySelector('#install-wizard .wizard-stepper li[aria-current]').textContent.includes('Activation')&&document.querySelector('#install-wizard .wizard-stepper li').classList.contains('completed')"),true);assert.equal(await run("document.querySelector('#wizard-next').disabled"),true);
  await until(()=>run("(()=>{const li=document.querySelector('#install-wizard .wizard-stepper li');return li.classList.contains('complete')&&li.querySelector('.wizard-step-check path')&&parseFloat(getComputedStyle(li.querySelector('.wizard-connector-fill')).width)>0&&getComputedStyle(li.querySelector('.wizard-step-check path')).strokeDashoffset==='0px'})()"));
  await pointer('#wizard-trust');await pointer('#wizard-back');await stage('Configuration');assert.equal(await run("document.querySelector('#wizard-results input').checked&&document.querySelector('#wizard-trust').checked"),true);
  await setUrl('https://example.com/nope');assert.equal(await run("document.querySelector('#wizard-next').disabled&&!document.querySelector('#wizard-trust').checked&&!document.querySelector('#wizard-results input')"),true);await pointer('#wizard-scan');
  await until(()=>run("document.querySelector('#wizard-feedback').dataset.error==='true'"));assert.equal(await run("document.querySelector('#wizard-feedback').textContent.includes('github.com')"),true);await snapshot('preview-error');
  await setUrl('https://github.com/fixture/repo/tree/main');await key('Enter');await until(()=>run("document.querySelector('#wizard-results input')&&!document.querySelector('#wizard-scan').disabled"));
  await pointer('#wizard-all');assert.equal(await run("document.querySelector('#wizard-count').textContent"),'1 dari 1 dipilih');await pointer('#wizard-none');assert.equal(await run("document.querySelector('#wizard-next').disabled"),true);await pointer('#wizard-all');await snapshot('configuration-selected');
  await pointer('#wizard-next');await stage('Activation');await wait(450);assert.deepEqual(await run("(()=>{const d=document.querySelector('#install-wizard'),v=d.querySelector('.wizard-viewport'),li=d.querySelector('.wizard-stepper li'),fill=li.querySelector('.wizard-connector-fill'),check=li.querySelector('.wizard-step-check');return {clone:!v.querySelector('.wizard-exit'),heads:[...v.querySelectorAll('h3')].filter(h=>h.getClientRects().length).length,noScroll:v.scrollWidth<=v.clientWidth+1,fillColor:getComputedStyle(fill).backgroundColor,fillWidth:fill.getBoundingClientRect().width>20,checkOpacity:getComputedStyle(check).opacity,checkWidth:check.getBoundingClientRect().width>=20,circle:li.querySelector('.wizard-step-circle').getBoundingClientRect().width}})()"),{clone:true,heads:1,noScroll:true,fillColor:'rgb(108, 59, 245)',fillWidth:true,checkOpacity:'1',checkWidth:true,circle:40});await snapshot('activation');await pointer('#wizard-trust');await pointer('#wizard-next');
  await until(()=>run("document.querySelector('#install-wizard').getAttribute('aria-busy')==='true'"));await key('Escape');assert.equal(await run("document.querySelector('#install-wizard').open&&document.querySelector('#wizard-back').disabled&&document.querySelector('#wizard-next').disabled"),true);
  await stage('Verification');await until(()=>run("!document.querySelector('#wizard-next').disabled"));assert.ok(fs.existsSync(path.join(home,'.gemini','config','skills','demo','SKILL.md')));assert.equal(await run('writes.install'),1);assert.equal(await run("document.querySelector('#wizard-back').hidden"),true);await snapshot('verification-unproven');
  await pointer('#wizard-start-proof');await until(()=>fs.existsSync(bridgeFile));
  mcp=spawn(process.execPath,[path.resolve(__dirname,'../bin/cli.js'),'mcp-serve'],{env:{...process.env,SANTRIHUB_BRIDGE_FILE:bridgeFile},stdio:['pipe','ignore','ignore']});mcp.stdin.write(JSON.stringify({jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2024-11-05',capabilities:{},clientInfo:{name:'fixture',version:'1'}}})+'\n');
  await until(()=>run("document.querySelector('#wizard-proof').classList.contains('proof-ok')"));assert.match(await run("document.querySelector('#wizard-proof').textContent"),/identitas IDE tidak diautentikasi.*MCP lain dan Skills belum terbukti/);await snapshot('verification-bridge');await pointer('#wizard-next');await stage('Done');await snapshot('install-done');await pointer('#wizard-next');await until(()=>run("!document.querySelector('#install-wizard').open"));assert.equal(await run("document.activeElement.id"),'add-item');
  await pointer('[data-page=skills]');await until(()=>run("!document.querySelector('#page-skills').hidden&&!document.querySelector('#page-skills').inert"));await wait(260);
  await until(()=>run("[...document.querySelectorAll('#installed-skills button')].some(b=>b.textContent==='Uninstall')"));await pointer('#installed-skills button');assert.equal(await run('document.activeElement.id'),'uninstall-cancel');await snapshot('uninstall-confirmation');await pointer('#uninstall-confirm');
  await until(()=>run("!document.querySelector('#uninstall-loading').hidden"));await key('Escape');assert.equal(await run("document.querySelector('#uninstall-dialog').open&&document.querySelector('#uninstall-cancel').disabled"),true);
  await until(()=>!fs.existsSync(path.join(home,'.gemini','config','skills','demo')));await until(()=>run("document.querySelector('#uninstall-cancel').textContent==='Done'&&!document.querySelector('#uninstall-cancel').disabled"));assert.equal(await run('writes.uninstall'),1);await snapshot('uninstall-done');await pointer('#uninstall-cancel');await until(()=>run("!document.querySelector('#uninstall-dialog').open&&document.activeElement.tagName==='H1'"));
  await pointer('[data-page=home]');await until(()=>run("!document.querySelector('#page-home').hidden&&!document.querySelector('#page-home').inert"));await pointer('#add-item');await until(()=>run("document.querySelector('#add-chooser').open"));
  for(const width of [320,390]){await client.call('Emulation.setDeviceMetricsOverride',{width,height:740,deviceScaleFactor:1,mobile:true});await noOverflow('#add-chooser');await snapshot('choice-mobile-'+width)}
  await pointer('[data-add-kind=mcp]');assert.equal(await run("document.querySelector('#wizard-title').textContent"),'Tambah MCP Servers');assert.equal(await run("document.querySelector('#wizard-proof').classList.contains('proof-ok')"),false);await noOverflow('#install-wizard');await snapshot('mcp-mobile');
  await pointer('#wizard-source-website');assert.equal(await run("!document.querySelector('#wizard-url').readOnly&&document.querySelector('#wizard-url').value==='https://reactbits.dev/get-started/mcp'"),true);await pointer('#wizard-scan');await until(()=>run("document.querySelector('#wizard-registry-copy')&&!document.querySelector('#wizard-registry').hidden"));assert.match(await run("document.querySelector('#wizard-registry').textContent"),/SETIAP project.*components.json|components.json.*SETIAP project/s);assert.match(await run("document.querySelector('#wizard-preset-config').textContent"),/shadcn@latest/);await noOverflow('#install-wizard');assert.equal(await run("[...document.querySelectorAll('#wizard-registry details')].every(d=>!d.open)"),true);await pointer('#wizard-registry details:first-child summary');assert.equal(await run("document.querySelector('#wizard-registry details').open"),true);await noOverflow('#install-wizard');await pointer('#wizard-registry-copy');await until(()=>run("document.querySelector('#wizard-feedback').textContent.includes('disalin')"));await pointer('#wizard-all');await pointer('#wizard-next');await stage('Activation');assert.match(await run("document.querySelector('#wizard-trust-hint').textContent"),/shadcn@latest/);await noOverflow('#install-wizard');await pointer('#wizard-trust');await pointer('#wizard-next');await stage('Verification');assert.deepEqual(JSON.parse(fs.readFileSync(config)).mcpServers.shadcn,{command:'npx',args:['shadcn@latest','mcp']});assert.equal(await run("document.querySelector('#wizard-proof').classList.contains('proof-ok')"),false);await pointer('#wizard-next');await stage('Done');await pointer('#wizard-next');await pointer('#add-item');await pointer('[data-add-kind=mcp]');
  for(const width of [320,390,1024,1280,1440]){await client.call('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:width<600});await wait(450);await noOverflow('#install-wizard');assert.equal(await run("(()=>{const d=document.querySelector('#install-wizard'),rail=d.querySelector('.wizard-rail').getBoundingClientRect(),main=d.querySelector('.wizard-main').getBoundingClientRect();return rail.bottom<=main.top+2&&Math.abs(rail.left-main.left)<2&&Math.abs(rail.width-main.width)<2})()"),true,`layout at ${width}px`);await snapshot('unified-'+width)}
  await setUrl('https://github.com/DavidHDev/react-bits');await pointer('#wizard-scan');await until(()=>run("document.querySelector('#wizard-feedback').textContent.includes('React Bits dikenali')"));assert.match(await run("document.querySelector('#wizard-preset-config').textContent"),/shadcn@latest/);
  await key('Tab');assert.equal(await run("document.activeElement.closest('#install-wizard')!==null"),true);await key('Escape');await until(()=>run("!document.querySelector('#install-wizard').open"));assert.equal(await run('document.activeElement.id'),'add-item');
  await client.call('Emulation.setDeviceMetricsOverride',{width:390,height:740,deviceScaleFactor:1,mobile:true});await wait(450);
  // Skills mobile surfaces, including activation footer, no horizontal overflow.
  await pointer('#add-item');await until(()=>run("document.querySelector('#add-chooser').open"));await pointer('[data-add-kind=skills]');await until(()=>run("document.querySelector('#install-wizard').open"));await setUrl('https://github.com/fixture/repo/tree/main');await key('Enter');await until(()=>run("document.querySelector('#wizard-results input')&&!document.querySelector('#wizard-scan').disabled"));await pointer('#wizard-all');await noOverflow('#install-wizard');await snapshot('configuration-mobile');await pointer('#wizard-next');await stage('Activation');await noOverflow('#install-wizard');await snapshot('activation-mobile');
  await pointer('#wizard-close');await until(()=>run("!document.querySelector('#install-wizard').open"));
  // One entrance only, no page exit, no replay on same menu, last rapid switch wins.
  assert.equal(await run("(()=>{go('repos');const animations=[...navigationAnimations];return !document.querySelector('#page-repos').hidden&&animations.length===1&&animations[0].effect.target===document.querySelector('#page-repos')&&animations[0].effect.getTiming().duration===480&&!animations[0].effect.getTiming().delay&&[...document.querySelector('#page-repos').children].every(el=>!el.getAnimations().length)&&!document.querySelector('#page-home').getAnimations().length})()"),true);
  assert.equal(await run("(()=>{go('repos');return navigationAnimations.length===0})()"),true);
  assert.equal(await run("(()=>{go('skills');const old=[...navigationAnimations];go('mcp');go('activity');return old.every(a=>a.playState==='idle')&&!document.querySelector('#page-activity').hidden&&!document.querySelector('#page-activity').inert&&Object.keys(PAGES).filter(p=>!document.querySelector('#page-'+p).hidden).length===1})()"),true);
  await client.call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});assert.equal(await run("getComputedStyle(document.querySelector('.wizard-check')).animationName"),'none');assert.equal(await run("(()=>{go('home');return navigationAnimations.length===0&&!document.querySelector('#page-home').inert})()"),true);
  await client.call('Emulation.setDeviceMetricsOverride',{width:1280,height:900,deviceScaleFactor:1,mobile:false});await run("document.querySelector('#logout').click();true");await until(()=>run("document.querySelector('#locked').open"));assert.equal(fs.existsSync(bridgeFile),false);assert.equal((await fetch(base+'/api/verification/status')).status,401);
 }catch(e){if(client)console.error((await client.call('Runtime.evaluate',{expression:"JSON.stringify({feedback:document.querySelector('#wizard-feedback')?.textContent,stage:document.querySelector('#wizard-stage')?.textContent,results:document.querySelector('#wizard-results')?.textContent,focus:document.activeElement?.id,url:document.querySelector('#wizard-url')?.value,busy:document.querySelector('#install-wizard')?.getAttribute('aria-busy'),open:[...document.querySelectorAll('dialog[open]')].map(d=>d.id),kind:document.querySelector('#wizard-title')?.textContent,html:document.querySelector('.wizard-viewport')?.innerHTML.slice(-900)})",returnByValue:true})).result.value);throw e}finally{client&&client.close();mcp&&mcp.kill();if(chrome){const exited=new Promise(r=>chrome.once('exit',r));chrome.kill();await Promise.race([exited,wait(2500)])}server&&server.closeAllConnections();remote&&remote.closeAllConnections();await Promise.all([server&&new Promise(r=>server.close(r)),remote&&new Promise(r=>remote.close(r))].filter(Boolean));fs.rmSync(home,{recursive:true,force:true,maxRetries:10,retryDelay:100})}
});
