'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),http=require('node:http'),{spawn}=require('node:child_process');
const {createDashboardServer}=require('../src/dashboard');
const CHROME=[process.env.CHROME_PATH,'C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'].filter(Boolean).find(fs.existsSync);
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,ms=8000){const end=Date.now()+ms;while(Date.now()<end){try{const value=await fn();if(value)return value}catch{}await wait(50)}throw new Error('browser fixture timeout')}
async function cdp(port){const page=await until(async()=>{const r=await fetch(`http://127.0.0.1:${port}/json`);return (await r.json()).find(p=>p.type==='page')});const ws=new WebSocket(page.webSocketDebuggerUrl);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});let id=0;const pending=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){const [r,j]=pending.get(m.id);pending.delete(m.id);m.error?j(new Error(m.error.message)):r(m.result)}};return {call(method,params={}){return new Promise((r,j)=>{const n=++id;pending.set(n,[r,j]);ws.send(JSON.stringify({id:n,method,params}))})},close(){ws.close()}}}

test('Chrome pointer wizard: pending guards, retry, steps, callback, uninstall, mobile and focus',{skip:CHROME?false:'Chrome not installed',timeout:45000},async()=>{
 const home=fs.mkdtempSync(path.join(process.env.TMPDIR||os.tmpdir(),'santri-browser-'));let chrome,server,remote,mcp,client;
 try{
  remote=http.createServer((req,res)=>{res.setHeader('content-type','application/json');res.end(JSON.stringify(req.url.endsWith('catalog')?{success:true,sources:[],mcpServers:[]}:{success:true,token:'fixture',user:{name:'Browser Fixture',is_premium:true}}))});await new Promise(r=>remote.listen(0,'127.0.0.1',r));
  const githubFetch=async url=>{await wait(250);return String(url).includes('/git/trees/')?new Response(JSON.stringify({tree:[{path:'demo/SKILL.md',type:'blob'}]}),{headers:{'content-type':'application/json'}}):new Response('---\nname: Demo\ndescription: Browser fixture\n---\nSafe',{headers:{'content-type':'text/plain'}})};
  const bridgeFile=path.join(home,'bridge.json');server=createDashboardServer({cwd:home,home,env:{},bridgeFile,githubFetch,apiUrl:`http://127.0.0.1:${remote.address().port}/api`});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`,post=(url,body={})=>fetch(base+url,{method:'POST',headers:{origin:base,'content-type':'application/json'},body:JSON.stringify(body)});
  const login=await(await post('/api/auth/login')).json(),state=new URL(login.url).searchParams.get('state');await post('/api/auth/callback',{state,ticket:'fixture_ticket'});
  const config=path.join(home,'.gemini','config','mcp_config.json');fs.mkdirSync(path.dirname(config),{recursive:true});fs.writeFileSync(config,JSON.stringify({mcpServers:{'santri-skills':{command:process.execPath,args:[path.resolve(__dirname,'../bin/cli.js'),'mcp-serve']}}}));
  const debug=29000+Math.floor(Math.random()*1000),profile=path.join(home,'chrome');chrome=spawn(CHROME,['--headless=new','--disable-gpu','--no-sandbox',`--remote-debugging-port=${debug}`,`--user-data-dir=${profile}`,base],{stdio:'ignore'});client=await cdp(debug);
  const run=async expression=>{const result=await client.call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.exception?.description||result.exceptionDetails.text);return result.result.value};
  const pointer=async selector=>{const point=await run(`(()=>{const b=document.querySelector(${JSON.stringify(selector)});b.scrollIntoView({block:'center',behavior:'instant'});const r=b.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`);await client.call('Input.dispatchMouseEvent',{type:'mouseMoved',...point});await client.call('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...point});await client.call('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...point})};
  const key=async(key,code=key)=>{const codes={Enter:13,Escape:27,Tab:9,' ':32},text=key==='Enter'?'\r':key===' '?' ':undefined;for(const type of ['keyDown','keyUp'])await client.call('Input.dispatchKeyEvent',{type,key,code,text:type==='keyDown'?text:undefined,windowsVirtualKeyCode:codes[key]||0})};
  const setUrl=async value=>run(`(()=>{const el=document.querySelector('#wizard-url');el.value=${JSON.stringify(value)};el.dispatchEvent(new Event('input',{bubbles:true}));el.focus()})()`);
  const stage=async name=>until(()=>run(`document.querySelector('#wizard-stage').textContent===${JSON.stringify(name)}`));
  const snapshot=async name=>{const dir=process.env.WIZARD_SCREENSHOT_DIR||path.join(process.env.TMPDIR||os.tmpdir(),'santrihub-wizard-evidence');fs.mkdirSync(dir,{recursive:true});const file=path.join(dir,name+'.png');const shot=await client.call('Page.captureScreenshot',{format:'png'});fs.writeFileSync(file,Buffer.from(shot.data,'base64'));console.log('Screenshot: '+file)};
  const noOverflow=async id=>assert.equal(await run(`(()=>{const d=document.querySelector(${JSON.stringify(id)}),r=d.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight&&d.scrollWidth<=d.clientWidth+1&&d.querySelector('.wizard-body').scrollWidth<=d.querySelector('.wizard-body').clientWidth+1})()`),true);
  await until(()=>run("document.querySelector('#add-item')&&!document.querySelector('#content').hidden"));
  await client.call('Emulation.setDeviceMetricsOverride',{width:1280,height:900,deviceScaleFactor:1,mobile:false});
  // Delay real requests, never synthesize success. Count writes to prove no duplicate submission.
  await run("window.writes={install:0,uninstall:0};window.originalFetch=window.fetch;window.fetch=async function(url,options){if(String(url).includes('/api/github/install')){writes.install++;await new Promise(r=>setTimeout(r,350))}if(String(url).includes('/api/uninstall')){writes.uninstall++;await new Promise(r=>setTimeout(r,350))}return originalFetch.call(this,url,options)}");
  assert.equal(await run("document.querySelector('#add-item').closest('#page-home')!==null && document.querySelector('main > header #add-item')===null && document.querySelector('#add-item').compareDocumentPosition(document.querySelector('.home-section'))===4"),true);
  await pointer('#add-item');await until(()=>run("document.querySelector('#add-chooser').open"));await snapshot('choice-desktop');
  await pointer('[data-add-kind=skills]');assert.equal(await run("document.activeElement.id"),'wizard-url');assert.equal(await run("document.querySelector('#wizard-next').disabled"),true);
  await setUrl('https://github.com/fixture/repo/tree/main');await key('Enter');
  await until(()=>run("!document.querySelector('#wizard-loading').hidden"));
  assert.equal(await run("['wizard-next','wizard-close','wizard-cancel','wizard-url','wizard-scan'].every(id=>document.getElementById(id).disabled)&&!document.querySelector('#wizard-loading progress').hasAttribute('value')"),true);
  await key('Escape');assert.equal(await run("document.querySelector('#install-wizard').open"),true);await snapshot('scan-pending');
  await until(()=>run("document.querySelector('#wizard-results input')&&!document.querySelector('#wizard-scan').disabled"));
  // Native checkbox remains keyboard-operable despite custom visual.
  await run("document.querySelector('#wizard-results input').focus()");await key(' ','Space');assert.equal(await run("document.querySelector('#wizard-count').textContent"),'1 dari 1 dipilih');
  await pointer('#wizard-next');await stage('Activation');assert.equal(await run("document.activeElement.id"),'wizard-stage');assert.equal(await run("document.querySelector('.wizard-stepper li[aria-current]').textContent.includes('Activation')&&document.querySelector('.wizard-stepper li').classList.contains('completed')"),true);assert.equal(await run("document.querySelector('#wizard-next').disabled"),true);
  await pointer('#wizard-trust');await pointer('#wizard-back');await stage('Configuration');assert.equal(await run("document.querySelector('#wizard-results input').checked&&document.querySelector('#wizard-trust').checked"),true);
  await setUrl('https://example.com/nope');assert.equal(await run("document.querySelector('#wizard-next').disabled&&!document.querySelector('#wizard-trust').checked&&!document.querySelector('#wizard-results input')"),true);await pointer('#wizard-scan');
  await until(()=>run("document.querySelector('#wizard-feedback').dataset.error==='true'"));assert.equal(await run("document.querySelector('#wizard-feedback').textContent.includes('github.com')"),true);await snapshot('preview-error');
  await setUrl('https://github.com/fixture/repo/tree/main');await key('Enter');await until(()=>run("document.querySelector('#wizard-results input')&&!document.querySelector('#wizard-scan').disabled"));
  await pointer('#wizard-all');assert.equal(await run("document.querySelector('#wizard-count').textContent"),'1 dari 1 dipilih');await pointer('#wizard-none');assert.equal(await run("document.querySelector('#wizard-next').disabled"),true);await pointer('#wizard-all');await snapshot('configuration-selected');
  await pointer('#wizard-next');await stage('Activation');await snapshot('activation');await pointer('#wizard-trust');await pointer('#wizard-next');
  await until(()=>run("document.querySelector('#install-wizard').getAttribute('aria-busy')==='true'"));await key('Escape');assert.equal(await run("document.querySelector('#install-wizard').open&&document.querySelector('#wizard-back').disabled&&document.querySelector('#wizard-next').disabled"),true);
  await stage('Verification');await until(()=>run("!document.querySelector('#wizard-next').disabled"));assert.ok(fs.existsSync(path.join(home,'.gemini','config','skills','demo','SKILL.md')));assert.equal(await run('writes.install'),1);assert.equal(await run("document.querySelector('#wizard-back').hidden"),true);await snapshot('verification-unproven');
  await pointer('#wizard-start-proof');await until(()=>fs.existsSync(bridgeFile));
  mcp=spawn(process.execPath,[path.resolve(__dirname,'../bin/cli.js'),'mcp-serve'],{env:{...process.env,SANTRIHUB_BRIDGE_FILE:bridgeFile},stdio:['pipe','ignore','ignore']});mcp.stdin.write(JSON.stringify({jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2024-11-05',capabilities:{},clientInfo:{name:'fixture',version:'1'}}})+'\n');
  await until(()=>run("document.querySelector('#wizard-proof').classList.contains('proof-ok')"));assert.match(await run("document.querySelector('#wizard-proof').textContent"),/identitas IDE tidak diautentikasi.*MCP lain dan Skills belum terbukti/);await snapshot('verification-bridge');await pointer('#wizard-next');await stage('Done');await snapshot('install-done');await pointer('#wizard-next');await until(()=>run("!document.querySelector('#install-wizard').open"));assert.equal(await run("document.activeElement.id"),'add-item');
  await pointer('[data-page=skills]');
  await until(()=>run("[...document.querySelectorAll('#installed-skills button')].some(b=>b.textContent==='Uninstall')"));await pointer('#installed-skills button');assert.equal(await run('document.activeElement.id'),'uninstall-cancel');await snapshot('uninstall-confirmation');await pointer('#uninstall-confirm');
  await until(()=>run("!document.querySelector('#uninstall-loading').hidden"));await key('Escape');assert.equal(await run("document.querySelector('#uninstall-dialog').open&&document.querySelector('#uninstall-cancel').disabled"),true);
  await until(()=>!fs.existsSync(path.join(home,'.gemini','config','skills','demo')));await until(()=>run("document.querySelector('#uninstall-cancel').textContent==='Done'&&!document.querySelector('#uninstall-cancel').disabled"));assert.equal(await run('writes.uninstall'),1);await snapshot('uninstall-done');await pointer('#uninstall-cancel');await until(()=>run("!document.querySelector('#uninstall-dialog').open&&document.activeElement.tagName==='H1'"));
  await pointer('[data-page=home]');await pointer('#add-item');await until(()=>run("document.querySelector('#add-chooser').open"));
  for(const width of [320,390]){await client.call('Emulation.setDeviceMetricsOverride',{width,height:740,deviceScaleFactor:1,mobile:true});await noOverflow('#add-chooser');await snapshot('choice-mobile-'+width)}
  await pointer('[data-add-kind=mcp]');assert.equal(await run("document.querySelector('#wizard-title').textContent"),'Tambah MCP Servers');assert.equal(await run("document.querySelector('#wizard-proof').classList.contains('proof-ok')"),false);await noOverflow('#install-wizard');await snapshot('mcp-mobile');
  await pointer('#wizard-source-website');assert.equal(await run("document.querySelector('#wizard-url').readOnly&&document.querySelector('#wizard-url').value==='https://reactbits.dev/get-started/mcp'"),true);await pointer('#wizard-scan');await until(()=>run("document.querySelector('#wizard-registry-copy')&&!document.querySelector('#wizard-registry').hidden"));assert.match(await run("document.querySelector('#wizard-registry').textContent"),/SETIAP project.*components.json|components.json.*SETIAP project/s);assert.match(await run("document.querySelector('#wizard-preset-config').textContent"),/shadcn@latest/);await noOverflow('#install-wizard');await pointer('#wizard-registry-copy');await until(()=>run("document.querySelector('#wizard-feedback').textContent.includes('disalin')"));await pointer('#wizard-all');await pointer('#wizard-next');await stage('Activation');assert.match(await run("document.querySelector('#wizard-trust-hint').textContent"),/shadcn@latest/);await noOverflow('#install-wizard');await pointer('#wizard-trust');await pointer('#wizard-next');await stage('Verification');assert.deepEqual(JSON.parse(fs.readFileSync(config)).mcpServers.shadcn,{command:'npx',args:['shadcn@latest','mcp']});assert.equal(await run("document.querySelector('#wizard-proof').classList.contains('proof-ok')"),false);await pointer('#wizard-next');await stage('Done');await pointer('#wizard-next');await pointer('#add-item');await pointer('[data-add-kind=mcp]');
  await key('Tab');assert.equal(await run("document.activeElement.closest('#install-wizard')!==null"),true);await key('Escape');await until(()=>run("!document.querySelector('#install-wizard').open"));assert.equal(await run('document.activeElement.id'),'add-item');
  // Skills mobile surfaces, including activation footer, no horizontal overflow.
  await pointer('#add-item');await pointer('[data-add-kind=skills]');await setUrl('https://github.com/fixture/repo/tree/main');await key('Enter');await until(()=>run("document.querySelector('#wizard-results input')&&!document.querySelector('#wizard-scan').disabled"));await pointer('#wizard-all');await noOverflow('#install-wizard');await snapshot('configuration-mobile');await pointer('#wizard-next');await stage('Activation');await noOverflow('#install-wizard');await snapshot('activation-mobile');
  await client.call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});assert.equal(await run("getComputedStyle(document.querySelector('.wizard-check')).animationName"),'none');await pointer('#wizard-close');
  await client.call('Emulation.setDeviceMetricsOverride',{width:1280,height:900,deviceScaleFactor:1,mobile:false});await run("document.querySelector('#logout').click();true");await until(()=>run("document.querySelector('#locked').open"));assert.equal(fs.existsSync(bridgeFile),false);assert.equal((await fetch(base+'/api/verification/status')).status,401);
 }catch(e){if(client)console.error((await client.call('Runtime.evaluate',{expression:"JSON.stringify({feedback:document.querySelector('#wizard-feedback')?.textContent,stage:document.querySelector('#wizard-stage')?.textContent,results:document.querySelector('#wizard-results')?.textContent,focus:document.activeElement?.id})",returnByValue:true})).result.value);throw e}finally{client&&client.close();mcp&&mcp.kill();if(chrome){const exited=new Promise(r=>chrome.once('exit',r));chrome.kill();await Promise.race([exited,wait(2500)])}server&&server.closeAllConnections();remote&&remote.closeAllConnections();await Promise.all([server&&new Promise(r=>server.close(r)),remote&&new Promise(r=>remote.close(r))].filter(Boolean));fs.rmSync(home,{recursive:true,force:true})}
});
