'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),http=require('node:http'),{spawn}=require('node:child_process');
const {createDashboardServer}=require('../src/dashboard');
const {removeInstalled,addMcpServer,configStatus}=require('../src/install');
const WEBSITE='https://reactbits.dev/get-started/mcp';
test('website preset preview is read-only, allowlisted, CSRF guarded; activation owned and unverified',()=>fixture(async({home,base,post,rawPost})=>{
 const file=path.join(home,'.gemini','config','mcp_config.json');
 assert.equal((await rawPost('/api/website/preview',{url:WEBSITE,scope:'global'})).status,403);
 for(const url of [WEBSITE+'/',WEBSITE+'?x=1','https://example.com/mcp','http://reactbits.dev/get-started/mcp'])assert.equal((await post('/api/website/preview',{url,scope:'global'})).status,400);
 const response=await post('/api/website/preview',{url:WEBSITE,scope:'global'});assert.equal(response.status,200);const p=await response.json();
 assert.deepEqual(p.entry,{command:'npx',args:['shadcn@latest','mcp']});assert.deepEqual(p.registry,{registries:{'@react-bits':'https://reactbits.dev/r/{name}.json'}});assert.match(p.warning,/@latest|unpinned/);assert.equal(fs.existsSync(file),false);
 const input={scope:'global',url:WEBSITE,previewId:p.previewId,confirm:true,confirmGlobal:true};
 assert.equal((await post('/api/website/install',input)).status,400);
 assert.equal((await post('/api/website/install',{...input,consentNetworkExecution:true,url:WEBSITE+'/'})).status,409);
 const installed=await post('/api/website/install',{...input,consentNetworkExecution:true});assert.equal(installed.status,200);assert.equal((await installed.json()).runtime,'unverified');
 const status=await(await fetch(base+'/api/status?scope=global')).json();assert.equal(status.mcp.servers.find(s=>s.name==='shadcn').managed,true);
 assert.equal(fs.existsSync(path.join(home,'components.json')),false);
 assert.equal((await post('/api/website/install',{...input,consentNetworkExecution:true})).status,409);
 assert.equal((await post('/api/uninstall',{scope:'global',kind:'mcp',id:'shadcn',confirm:true,confirmGlobal:true})).status,200);assert.ok(fs.existsSync(file+'.bak'));assert.equal(JSON.parse(fs.readFileSync(file)).mcpServers.shadcn,undefined);
 await post('/api/auth/logout');assert.equal((await post('/api/website/preview',{scope:'global',url:WEBSITE})).status,401);
}));
test('owned website install rejects existing identical shadcn, preserves config and backup, refuses modified ownership',()=>{
 const home=tmp(),file=path.join(home,'mcp.json'),entry={command:'npx',args:['shadcn@latest','mcp']};try{
 const original=JSON.stringify({private:'fixture',mcpServers:{shadcn:entry}});fs.writeFileSync(file,original);fs.writeFileSync(file+'.bak','prior backup');
 assert.throws(()=>addMcpServer(file,entry,'shadcn',{preset:'react-bits'}),/Backup|sudah ada/);assert.equal(fs.readFileSync(file,'utf8'),original);assert.equal(fs.readFileSync(file+'.bak','utf8'),'prior backup');
 fs.writeFileSync(file,JSON.stringify({mcpServers:{other:{command:'keep'}}}));assert.throws(()=>addMcpServer(file,entry,'shadcn',{preset:'react-bits'}),/Backup/);assert.equal(fs.readFileSync(file+'.bak','utf8'),'prior backup');fs.rmSync(file+'.bak');fs.writeFileSync(file,original);assert.throws(()=>addMcpServer(file,entry,'shadcn',{preset:'react-bits'}),/sudah ada/);fs.writeFileSync(file,JSON.stringify({mcpServers:{other:{command:'keep'}}}));addMcpServer(file,entry,'shadcn',{preset:'react-bits'});assert.deepEqual(Object.keys(JSON.parse(fs.readFileSync(file+'.bak')).mcpServers),['other']);
 let cfg=JSON.parse(fs.readFileSync(file));cfg.mcpServers.shadcn.args=['changed'];fs.writeFileSync(file,JSON.stringify(cfg));assert.throws(()=>removeInstalled({kind:'mcp',id:'shadcn',mcpFile:file}),/milik|dikenal/);
 cfg.mcpServers.shadcn=entry;fs.writeFileSync(file,JSON.stringify(cfg));removeInstalled({kind:'mcp',id:'shadcn',mcpFile:file});assert.deepEqual(Object.keys(JSON.parse(fs.readFileSync(file)).mcpServers),['other']);
 }finally{fs.rmSync(home,{recursive:true,force:true})}
});
const tmp=()=>fs.mkdtempSync(path.join(process.env.TMPDIR||os.tmpdir(),'santri-wizard-'));
async function fixture(fn){const home=tmp();const remote=http.createServer((req,res)=>{res.setHeader('content-type','application/json');res.end(JSON.stringify(req.url.endsWith('catalog')?{success:true,sources:[],mcpServers:[]}:{success:true,token:'fixture-only',user:{name:'Fixture',is_premium:true}}))});await new Promise(r=>remote.listen(0,'127.0.0.1',r));const server=createDashboardServer({cwd:home,home,env:{},apiUrl:`http://127.0.0.1:${remote.address().port}/api`,bridgeFile:path.join(home,'bridge.json')});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`,post=(url,body={})=>fetch(base+url,{method:'POST',headers:{origin:base,'content-type':'application/json'},body:JSON.stringify(body)});try{const state=new URL((await (await post('/api/auth/login')).json()).url).searchParams.get('state');const csrf=(await (await post('/api/auth/callback',{state,ticket:'fixture_ticket'})).json()).csrf;await fn({home,base,post:(url,b={})=>post(url,{_csrf:csrf,...b}),rawPost:post})}finally{server.closeAllConnections();remote.closeAllConnections();await Promise.all([new Promise(r=>server.close(r)),new Promise(r=>remote.close(r))]);fs.rmSync(home,{recursive:true,force:true})}}
test('uninstall refuses linked ancestors and backup files without changing foreign data',()=>{const home=tmp();try{const real=path.join(home,'real'),alias=path.join(home,'alias');fs.mkdirSync(path.join(real,'own'),{recursive:true});fs.writeFileSync(path.join(real,'own','.santri-skills.json'),JSON.stringify({source:'fixture',installedAt:new Date().toISOString()}));fs.symlinkSync(real,alias,'junction');assert.throws(()=>removeInstalled({kind:'skill',id:'own',skillsDir:alias}),/Symlink|junction/);const file=path.join(home,'mcp.json'),foreign=path.join(home,'foreign.json');fs.writeFileSync(file,JSON.stringify({mcpServers:{'santri-skills':{command:'npx',args:['-y','santriverse-skills','mcp-serve']}}}));fs.writeFileSync(foreign,'KEEP');fs.linkSync(foreign,file+'.bak');assert.throws(()=>removeInstalled({kind:'mcp',id:'santri-skills',mcpFile:file}),/Hardlink/);assert.equal(fs.readFileSync(foreign,'utf8'),'KEEP')}finally{fs.rmSync(home,{recursive:true,force:true})}});
test('dashboard rejects project scope on reads and writes',()=>fixture(async({base,post})=>{assert.equal((await fetch(base+'/api/status?scope=project')).status,400);assert.equal((await fetch(base+'/api/targets?scope=project')).status,400);assert.equal((await post('/api/verify',{scope:'project'})).status,400);assert.equal((await post('/api/local/skills/preview',{scope:'project'})).status,400)}));
test('bridge proof requires active global config, expires and invalidates when config changes',()=>fixture(async({home,base,post})=>{const file=path.join(home,'.gemini','config','mcp_config.json');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify({mcpServers:{'santri-skills':{command:process.execPath,args:[path.resolve(__dirname,'../bin/cli.js'),'mcp-serve']}}}));const started=await post('/api/verification/start',{scope:'global'});assert.equal(started.status,200);const {challenge}=await started.json();const bridge=JSON.parse(fs.readFileSync(path.join(home,'bridge.json'),'utf8'));assert.equal((await fetch(base+'/api/verification/status')).status,200);const callback=(nonce,token)=>fetch(base+'/api/verification/bridge',{method:'POST',headers:{'content-type':'application/json','x-santrihub-bridge':token},body:JSON.stringify({challenge:nonce,event:'tool'})});assert.equal((await callback('wrong',bridge.token)).status,403);assert.equal((await callback(challenge,'wrong')).status,403);assert.equal((await callback(challenge,bridge.token)).status,200);assert.equal((await callback(challenge,bridge.token)).status,409);let status=await(await fetch(base+'/api/verification/status')).json();assert.equal(status.verified,true);fs.writeFileSync(file,JSON.stringify({mcpServers:{'santri-skills':{command:'changed'}}}));status=await(await fetch(base+'/api/verification/status')).json();assert.equal(status.verified,false);assert.doesNotMatch(JSON.stringify(status),/token|challenge/);await post('/api/auth/logout');assert.equal((await fetch(base+'/api/verification/status')).status,401);assert.equal(fs.existsSync(path.join(home,'bridge.json')),false)}));
test('real MCP stdio process reports callback without browser capability',()=>fixture(async({home,base,post})=>{
 const config=path.join(home,'.gemini','config','mcp_config.json');fs.mkdirSync(path.dirname(config),{recursive:true});fs.writeFileSync(config,JSON.stringify({mcpServers:{'santri-skills':{command:process.execPath,args:[path.resolve(__dirname,'../bin/cli.js'),'mcp-serve']}}}));
 const started=await post('/api/verification/start',{scope:'global'});assert.equal(started.status,200);assert.doesNotMatch(JSON.stringify(await started.json()),/"token"/);
 const child=spawn(process.execPath,[path.resolve(__dirname,'../bin/cli.js'),'mcp-serve'],{env:{...process.env,SANTRIHUB_BRIDGE_FILE:path.join(home,'bridge.json')},stdio:['pipe','pipe','pipe']});
 try{
  const line=new Promise((resolve,reject)=>{let output='';const timer=setTimeout(()=>reject(new Error('MCP initialize timeout')),5000);child.stdout.on('data',chunk=>{output+=chunk;const end=output.indexOf('\n');if(end!==-1){clearTimeout(timer);resolve(JSON.parse(output.slice(0,end)))}});child.once('error',reject);child.once('exit',code=>reject(new Error('MCP exited '+code)))});
  child.stdin.write(JSON.stringify({jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2024-11-05',capabilities:{},clientInfo:{name:'fixture',version:'1'}}})+'\n');
  assert.equal((await line).result.serverInfo.name,'santri-skills');
  let proof;for(let i=0;i<40;i++){proof=await(await fetch(base+'/api/verification/status')).json();if(proof.verified)break;await new Promise(r=>setTimeout(r,50))}
  assert.equal(proof.verified,true);assert.equal(proof.evidence.event,'initialize');assert.equal(proof.evidence.identityAuthenticated,false);
 }finally{child.kill();child.stdin.end()}
}));
test('safe uninstall refuses foreign skill, invalid marker and MCP collision, backs up config',()=>{const home=tmp();try{const dir=path.join(home,'skills'),file=path.join(home,'mcp_config.json');fs.mkdirSync(path.join(dir,'foreign'),{recursive:true});fs.writeFileSync(path.join(dir,'foreign','SKILL.md'),'foreign');assert.throws(()=>removeInstalled({kind:'skill',id:'foreign',skillsDir:dir,mcpFile:file}),/milik|marker/);const malformed=path.join(dir,'malformed');fs.mkdirSync(malformed);fs.writeFileSync(path.join(malformed,'SKILL.md'),'keep');fs.writeFileSync(path.join(malformed,'.santri-skills.json'),'{');assert.throws(()=>removeInstalled({kind:'skill',id:'malformed',skillsDir:dir,mcpFile:file}),/milik|marker/);assert.equal(fs.readFileSync(path.join(malformed,'SKILL.md'),'utf8'),'keep');const own=path.join(dir,'own');fs.mkdirSync(own);fs.writeFileSync(path.join(own,'SKILL.md'),'own');fs.writeFileSync(path.join(own,'.santri-skills.json'),JSON.stringify({source:'fixture',installedAt:new Date().toISOString()}));const result=removeInstalled({kind:'skill',id:'own',skillsDir:dir,mcpFile:file});assert.equal(result.removed,true);assert.equal(fs.existsSync(own),false);fs.writeFileSync(file,JSON.stringify({mcpServers:{foreign:{command:'keep'},'santri-skills':{command:'npx',args:['-y','santriverse-skills','mcp-serve']}}}));removeInstalled({kind:'mcp',id:'santri-skills',skillsDir:dir,mcpFile:file});assert.deepEqual(Object.keys(JSON.parse(fs.readFileSync(file)).mcpServers),['foreign']);assert.ok(fs.existsSync(file+'.bak'));assert.throws(()=>removeInstalled({kind:'mcp',id:'foreign',skillsDir:dir,mcpFile:file}),/milik|dikenal/)}finally{fs.rmSync(home,{recursive:true,force:true})}});
